### ISSUE TITLE
How to run?

### ISSUE THREAD

**Issue by davhdavh** [antlr/antlr4-javascript#10]
How does one try this out?

I tried putting the stg file with the antlr-4.4-complete.jar, but it still says javascript is not supported.

**Comment by ericvergnaud** [comment]
Hi,

this is not officially released yet, but should be in the upcoming 2 weeks.

Eric

**Comment by thirdcreed** [comment]
Awesome, very excited about this project. Thanks a lot.

**Comment by ericvergnaud** [comment]
A pre-release is available here: http://www.antlr.org/download.html
