### ISSUE TITLE
Can we get a removeErrorListeners function added to Recognizer.js (like the on in the Java runtime)?

### ISSUE THREAD

**Issue by mikecargal** [antlr/antlr4-javascript#15]
Once I've plugged in y own listener, I'd like to shut down the writing to the console.

**Comment by ericvergnaud** [comment]
note that you can already do that in an unclean way: r._listeners = [mylistener];
will add to the TODO list

**Comment by mikecargal** [comment]
So, now you’re able to read my code??  Much be a leak in our security :)

I did exactly that (with a comment to remove the nastiness once there was an “proper” way to do it)

**Comment by ericvergnaud** [comment]
:-)
