### ISSUE TITLE
Make available via package manager (npm, bower)

### ISSUE THREAD

**Issue by aeschylus** [antlr/antlr4-javascript#16]

**Comment by ericvergnaud** [comment]
Hi,
maybe you can provide a pull request with details on how to do this?
Eric

**Comment by ericvergnaud** [comment]
Done!

**Comment by gulfaraz** [comment]
What is the bower package name ? I cannot find **antlr** on `bower search`

**Comment by ericvergnaud** [comment]
Hi, 
the package is npm compatible, but not registered with bower.
from bower docs, I understand it can be downloaded from github.
am I missing something?
