### ISSUE TITLE
Rules named function cause output with syntax errors

### ISSUE THREAD

**Issue by TomLottermann** [antlr/antlr4-javascript#17]
A subrule with the name `function` causes syntax errors.

```
grammar TestGrammar;

test: function=(A|B);

A: 'a';
B: 'b';
```

This is caused by the fact that `function` is not part of the javascript keywords.

**Comment by TomLottermann** [comment]
I just recognized the original list: is this just copy-pasted from the java source?
There might actually be many more missing

**Comment by ericvergnaud** [comment]
possibly a task that has been left aside, and is worth double checking

**Comment by TomLottermann** [comment]
I added a new commit, which actually includes all the keywords specified by Mozilla:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Lexical_gramma

**Comment by ericvergnaud** [comment]
Cool.
Is your name already on the contributor/agreement list?

Eric

**Comment by TomLottermann** [comment]
No. But I created this pull request:
https://github.com/antlr/antlr4/pull/806
