### ISSUE TITLE
ParseTreeVisitor is missing some members

### ISSUE THREAD

**Issue by samueldjack** [antlr/antlr4-javascript#23]
ParseTreeVisitor seems to be missing some members compared with AbstractParseTreeVisitor.

In order for visitors to work at all, I had to implement the following methods in my visitor:

* visit
* visitChildren
* visitTerminal
* visitErrorNode
* shouldVisitNextChild
* aggregateResult

**Comment by ericvergnaud** [comment]
Hi,
please feel free to submit a pull request. I don't use visitors myself, so will happily consider proposals.

**Comment by ericvergnaud** [comment]
In the absence of proposal, I will close this in a week.

**Comment by ericvergnaud** [comment]
Closing in the absence of proposal.

**Comment by mlevin2** [comment]
@samueldjack Any follow-up to this? I'm facing the same issue.

**Comment by ericvergnaud** [comment]
Hi,
please submit a PR with your proposals so we can review them.
Cheers,
Eric

**Comment by rektide** [comment]
Could someone (@samueldjack?) please provide an example of how they did implement some of these methods? Even if it's custom coding for a specific grammar, even if it's woefully incomplete, it'd be helpful to have some kind of starting place. I'm not sure where to begin with a visit implementation.

**Comment by krzkaczor** [comment]
Here are results of my experiments (I will create PR in few days - I need to test it and maybe extend)

I use ES6 and lodash in my examples.

First: visit and visit atom functions (it supports visiting children etc.) ORIGINAL visit by @azukaar

```
    visit(ctx) {
        if (_.isArray(ctx)) {
            var children = ctx;

            return children.map(child => this.visitAtom(child));
        } else {
            return this.visitAtom(ctx);
        }
    }

    visitAtom(ctx) {
        if (_.isUndefined(ctx.parser)) {
            return;
        }

        //Get the name of the node
        var name = ctx.parser.ruleNames[ctx.ruleIndex];
        //Sharpen the name of the function VisitNode()
        var funcName = "visit" + name.charAt(0).toUpperCase() + name.slice(1);
        //Call it
        return this[funcName](ctx);
    }
```

and here's autoVisit function - autogenerated visit functions are visiting first children automatically.

```
var autoVisitor = function(visitor) {
    _.chain(visitor.prototype).pairs().filter((keyAndValue) => {
        return _.startsWith(keyAndValue[0], 'visit');
    }).forEach(keyAndValue => {
        var [key, value] = keyAndValue;

        visitor.prototype[key] = function(ctx) {
            return this.visit(ctx.children[0]);
        }
    }).run();
};
```
It would be great to hear suggestions etc.
