### ISSUE TITLE
LexerATNSimulator.prototype.getReachableConfigSet infinite loop

### ISSUE THREAD

**Issue by multiarc** [antlr/antlr4-javascript#25]
The issue appears only after Lexer.prototype.recover function on rare cases.
It's getting into closure and grow up configs array constantly adding new unique config in the set, I try to keep it going up until it reaches the 20k items in the config list.
Also on the C# target runtime (4.5) it's working just fine and say about recognition errors.
Here is the part of lexis grammar:
```antlr
mode CALL;

CALL_COMMENT:
	'@*' .*? '*@' -> skip;

CALL_OUT_WS: 
         WS+ -> skip;

CSHARP_START:
	'@' -> pushMode(CS);

CALL_OUT_PARAMEND: 
	')' -> type(OUT_PARAMEND), popMode;

CALL_OUT_PARAMSTART: 
	'(' -> type(OUT_PARAMSTART), pushMode(CALL);

CALL_OUT_DELIM: 
	':' -> type(DELIM);

CALL_OUT_ID: 
        ID_TOKEN -> type(ID);

CALL_LINE_TERMINATE: 
	';' WS* -> type(LINE_TERMINATE), popMode, popMode;
```
And here is the text that cause the infinite loop:
((:){{

**Comment by sharwell** [comment]
My guess is it's not actually an infinite loop, but that this runtime faces the issue described in antlr/antlr4-python2#24.

**Comment by ericvergnaud** [comment]
Sam,
there is no room for opinions here. Please stay out of this.
Eric

**Comment by sharwell** [comment]
@ericvergnaud The information necessary to examine the key lookup algorithm for this set is included in the linked issue, so I did not feel it needed to be duplicated here. The primary symptom of pathological behavior in the algorithm is the following (emphasis mine):

> It's **getting into closure and grow up configs array constantly adding new unique config in the set**, I try to keep it going up until it reaches the 20k items in the config list.

I'm not sure which part of this is an opinion?

**Comment by ericvergnaud** [comment]
#24 was itself based on opinions rather than reproducible tests
and the javascript hash related code is completely different from the Python code

**Comment by ericvergnaud** [comment]
Aliaksandr,
it seems your code fragment is not sufficient to build a test, since it refers to undefined modes and tokens.
Can you provide a grammar we can use?
Eric

**Comment by sharwell** [comment]
I looked into my hypothesis, and it seems the implementation in JavaScript uses a different implementation of this set, as seen here:
https://github.com/antlr/antlr4-javascript/blob/master/src/antlr4/atn/ATNConfigSet.js#L60-L71

**Comment by multiarc** [comment]
Ok I've got exact issue with this, I will post full proof grammar in a bit, WS was defined wrongly as WHITESPACE+, when I changed it to WHITESPACE

**Comment by multiarc** [comment]
Ok, here we go. 
Lexer:
```antlr
lexer grammar TestLexer;

tokens { ID, DELIM, COMMENT, OUT_PARAMSTART, OUT_PARAMEND, LINE_TERMINATE }

/*
 * Lexer Rules
 */

fragment ID_TOKEN: IDENTIFIER;

fragment IDENTIFIER: IDENTIFIER_START IDENTIFIER_PART*;

fragment IDENTIFIER_START: 
	[a-zA-Zа-яА-Я_]
	| UNICODE_ESCAPE
	;

fragment IDENTIFIER_PART:
	IDENTIFIER_START
	| UNICODE_ESCAPE
	| [\.\+0-9]
	;

fragment UNICODE_ESCAPE:
	'\\u' HEX_DIGIT HEX_DIGIT HEX_DIGIT HEX_DIGIT
	| '\\U' HEX_DIGIT HEX_DIGIT HEX_DIGIT HEX_DIGIT HEX_DIGIT HEX_DIGIT HEX_DIGIT HEX_DIGIT
	;

fragment HEX_DIGIT:
	'0'..'9'
	| 'a'..'f'
	| 'A'..'F'
	;

fragment WS: WHITESPACE+;

fragment NEW_LINE:
	[\r\n] | '\u0085' | '\u2028' | '\u2029';

fragment WHITESPACE: NEW_LINE
	| [ \t\f] 
	| '\u000B'
	| '\u00A0' 
	| '\u1680' 
	| '\u2000'..'\u200A' 
	| '\u202F' 
	| '\u205F' 
	| '\u3000'
	;

fragment PARA_ST: '(';
fragment PARA_CL: ')';
fragment EXT_DELIM: ':';
fragment LINE_TERM: ';';
fragment COMMENT_BLOCK: '@*' .*? '*@';

CALL_COMMENT:
	COMMENT_BLOCK -> skip;

CALL_OUT_PARAMEND: 
	PARA_CL -> type(OUT_PARAMEND), popMode;

CALL_OUT_PARAMSTART: 
	PARA_ST -> type(OUT_PARAMSTART), pushMode(DEFAULT_MODE);

CALL_OUT_DELIM: 
	EXT_DELIM -> type(DELIM);

CALL_OUT_ID: ID_TOKEN -> type(ID);

CALL_LINE_TERMINATE: 
	LINE_TERM WS* -> type(LINE_TERMINATE), popMode, popMode;

CALL_OUT_WS: WS+ -> skip;
```
Parser:
```antlr
parser grammar TestParser;
options { tokenVocab=TestLexer; }

/*
 * Parser Rules
 */

chain: call (DELIM call)*;

call: named_call
	| unnamed_call
	;

named_call: ID OUT_PARAMSTART ID? OUT_PARAMEND
	| ID OUT_PARAMSTART chain OUT_PARAMEND
	;

unnamed_call: OUT_PARAMSTART ID? OUT_PARAMEND
	| OUT_PARAMSTART chain OUT_PARAMEND
	;
```
Test string is:
```
() any text 1
		        
		    any text 2
any text 3
```
If you remove any text 3 and replace any text 2 to single symbol runtime finishes in a minute or so, if you keep it or add more it seems I can't wait the time it finishes. Seems like it's adding as much configs as much text we have after first unrecognized token

If I replace
```antlr
fragment WS: WHITESPACE+;
```
with
```antlr
fragment WS: WHITESPACE;
```

It's working just good.
