### ISSUE TITLE
Customized references to root JavaScript files with absolute reference support.

### ISSUE THREAD

**Issue by heroicefforts** [antlr/antlr4-javascript#28]
By convention, my Java web app's JavaScript is under the server path /js.  Thus, I would like to have the antlr runtime nested somewhere underneath e.g. /js/antlr/... and my generated code under /js/gen/somepath.  However, when I crack open the generated code, I see the assumption of "require('antlr/index')".  Is there a way to customize this akin to the -Dpackage option supported for the other languages?

I also noticed that require('/js/...') does not properly reference to the server root (http://myserver/js/...), but instead includes the servlet context (http://myserver/myservlet/js/...)?  The location of the javascript will not change, but my servlet contexts will, so I cannot reference this javascript from a common server side include file without an absolute reference to the lexer, parser, and antlr runtime index javascript files.  Is there a syntax for require that forces an absolute path?

**Comment by ericvergnaud** [comment]
Hi,
thanks for the detailed explanation.
require is not part of antlr.
Check the license agreement, but I'm pretty sure you can modify it to suit your -legitimate- needs.
Cheers,
Eric
