### ISSUE TITLE
Caused by requirejs maybe?

### ISSUE THREAD

**Issue by hanwencheng** [antlr/antlr4-javascript#30]
I have wrapped all the antlr4 source file in [requirejs module](
http://requirejs.org/docs/commonjs.html#manualconversion)

And with the simplest module format

        define([
            'antlr4/index'
        ], function(anltr){
            //do something
        });

there is always a error happened here in 81 line of ParserRuleContext.js

        Uncaught TypeError: Cannot read property 'prototype' of undefined.

I have implement the antlr4 with lib/require.js in the repository, but now I have no idea if this problem is caused by requirejs

**Comment by ericvergnaud** [comment]
Hi,
this is not an antlr issue, which has been successfully tested in various browsers, using Smoothie's synchronous require function. Asynchronous loading of antlr fragments does not make sense, so there is no support for it.
