### ISSUE TITLE
Unable to execute the parser for SQLite.g4 in JavaScript Target

### ISSUE THREAD

**Issue by Erickrus** [antlr/antlr4-javascript#31]
Unable to parse the input string

I’m using ANTLR4 with some of the enhancement on JavaScript side. Fortunately, we have multiple targets of ANTLR4 now. 

I’m working on a “Query Reference Tool”. The idea to me is to remove all comments, and mask literal with paddings of # in SQL. So, I need a purify() function for SQL. I’ve tested in Java Target with SQLite.g4 in standard repository and it works.

	private static String purify(String sql) {
		SQLiteLexer l;
		Token t;
		
		l = new SQLiteLexer(new ANTLRInputStream(sql));
		CommonTokenStream tokens = new CommonTokenStream(l);

		String result = "";
		while (!(t = l.nextToken()).getText().equals("<EOF>")) {
			String type = SQLiteLexer.tokenNames[t.getType()];
			if (!type.equals("MULTILINE_COMMENT") && !type.equals("SINGLE_LINE_COMMENT")) {
				if (type.equals("STRING_LITERAL")) {
					result += "'" + padding('#', t.getText().length() - 2)
							+ "'";
				} else if (type.equals("SPACES")) {
					result += " ";
				} else if (type.startsWith("K_")) {
					result += t.getText().toUpperCase();
				} else {
					result += t.getText();
				}
			}
		}
		return result;
	}
 
While I’m deploying this function to JavaScript (in chrome), there’re some issues during the lexer phase, I don't know what’s wrong with it. It seems some value in the atn part is undefined, when I traced into the functions. (One more thing, I’ve did some modification on the runtime JavaScript, simply remove require(…) and exports… , since it is just for a local webpage). I think these changes won’t matter the whole package (no syntax errors).

As I removed the exports and require clause, I put them as following order

<script src='antlr4\Utils.js' ></script>
<script src='antlr4\Token.js' ></script>
<script src='antlr4\BufferedTokenStream.js' ></script>
<script src='antlr4\CommonTokenFactory.js' ></script>
<script src='antlr4\CommonTokenStream.js' ></script>
<script src='antlr4\FileStream.js' ></script>
<script src='antlr4\InputStream.js' ></script>
<script src='antlr4\IntervalSet.js' ></script>
<script src='antlr4\Recognizer.js' ></script>
<script src='antlr4\Lexer.js' ></script>
<script src='antlr4\LL1Analyzer.js' ></script>
<script src='antlr4\tree\Tree.js' ></script>
<script src='antlr4\tree\Trees.js' ></script>
<script src='antlr4\Parser.js' ></script>
<script src='antlr4\RuleContext.js' ></script>
<script src='antlr4\ParserRuleContext.js' ></script>
<script src='antlr4\PredictionContext.js' ></script>
<script src='antlr4\dfa\DFASerializer.js' ></script>
<script src='antlr4\dfa\DFAState.js' ></script>
<script src='antlr4\atn\ATN.js' ></script>
<script src='antlr4\atn\ATNConfig.js' ></script>
<script src='antlr4\atn\ATNConfigSet.js' ></script>
<script src='antlr4\atn\ATNDeserializationOptions.js' ></script>
<script src='antlr4\atn\ATNDeserializer.js' ></script>
<script src='antlr4\atn\ATNSimulator.js' ></script>
<script src='antlr4\atn\ATNState.js' ></script>
<script src='antlr4\atn\ATNType.js' ></script>
<script src='antlr4\atn\LexerAction.js' ></script>
<script src='antlr4\atn\LexerActionExecutor.js' ></script>
<script src='antlr4\atn\LexerATNSimulator.js' ></script>
<script src='antlr4\atn\ParserATNSimulator.js' ></script>
<script src='antlr4\atn\PredictionMode.js' ></script>
<script src='antlr4\atn\SemanticContext.js' ></script>
<script src='antlr4\atn\Transition.js' ></script>
<script src='antlr4\dfa\DFA.js' ></script>
<script src='antlr4\error\Errors.js' ></script>
<script src='antlr4\error\ErrorListener.js' ></script>
<script src='antlr4\error\DiagnosticErrorListener.js' ></script>
<script src='antlr4\error\ErrorStrategy.js' ></script>
<script src='SQLiteLexer.js'></script>
<script src='SQLiteListener.js'></script>
<script src='SQLiteParser.js'></script>

My codes are like this:

var input = "SELECT * FROM DUAL;";
var chars = new InputStream(input);
var lexer = new SQLiteLexer(chars);

var t;
while (!(t = lexer.nextToken())) {
   //TODO: complete the purify function in javascript
   console.log(t.getText());
}

This is the trace stack, I put the variable during the process as comments, hopefully this could help to figure out the problem

Lexer.js : 153
ttype = this._interp.match(this._input, this._mode);
//this._input == "SELECT * FROM DUAL;"
//this._mode == 0

LexerATNSimulator.js : 128
return this.matchATN(input);
//dfa == DFA {atnStartState: StarBlockStartState, decision: 0, _states: DFAStatesSet, s0: null, precedenceDfa: false…}

LexerATNSimulator.js : 146
var startState = this.atn.modeToStartState[this.mode];
//this.atn.modeToStartState == []
//startState == undefined
//this.mode == 0

LexerATNSimulator.js : 152
var s0_closure = this.computeStartState(input, startState);
//input == InputStream {name: "<empty>", strdata: "SELECT * FROM DUAL;", _index: 0, data: Array[19], _size: 19…}
//startState == undefined

LexerATNSimulator.js : 364
for (var i = 0; i < p.transitions.length; i++) {
//p == undefined
//Here notifyListeners and error out, because p is undefined

**Comment by Erickrus** [comment]
Here's the order of my script reference chain , it may impact the initialization, I guess.
script src='antlr4\Utils.js'
script src='antlr4\Token.js'
script src='antlr4\BufferedTokenStream.js'
script src='antlr4\CommonTokenFactory.js'
script src='antlr4\CommonTokenStream.js'
script src='antlr4\FileStream.js'
script src='antlr4\InputStream.js'
script src='antlr4\IntervalSet.js'
script src='antlr4\Recognizer.js'
script src='antlr4\Lexer.js'

script src='antlr4\LL1Analyzer.js'

script src='antlr4\tree\Tree.js'
script src='antlr4\tree\Trees.js'
script src='antlr4\Parser.js'
script src='antlr4\RuleContext.js'
script src='antlr4\ParserRuleContext.js'
script src='antlr4\PredictionContext.js'



script src='antlr4\dfa\DFASerializer.js'
script src='antlr4\dfa\DFAState.js'

script src='antlr4\atn\ATN.js'
script src='antlr4\atn\ATNConfig.js'
script src='antlr4\atn\ATNConfigSet.js'
script src='antlr4\atn\ATNDeserializationOptions.js'
script src='antlr4\atn\ATNDeserializer.js'
script src='antlr4\atn\ATNSimulator.js'
script src='antlr4\atn\ATNState.js'
script src='antlr4\atn\ATNType.js'
script src='antlr4\atn\LexerAction.js'
script src='antlr4\atn\LexerActionExecutor.js'
script src='antlr4\atn\LexerATNSimulator.js'
script src='antlr4\atn\ParserATNSimulator.js'
script src='antlr4\atn\PredictionMode.js'
script src='antlr4\atn\SemanticContext.js'
script src='antlr4\atn\Transition.js'
script src='antlr4\dfa\DFA.js'



script src='antlr4\error\Errors.js'
script src='antlr4\error\ErrorListener.js'
script src='antlr4\error\DiagnosticErrorListener.js'
script src='antlr4\error\ErrorStrategy.js'


script src='SQLiteLexer.js'
script src='SQLiteListener.js'
script src='SQLiteParser.js'

**Comment by ericvergnaud** [comment]
Why don't use the provided require?
It has been tested over and over

**Comment by Erickrus** [comment]
Because I just put it locally, not deployed to a site yet.
"requires" need  something like XMLHttpRequest to work.

**Comment by ericvergnaud** [comment]
Wouldn't you be better tweaking 'require' so it works with file:// protocol?
The antlr runtime relies heavily on 'require', I will not support hand written dependency management.
Also, this subject would be better on google groups, since it is not an issue.
