### ISSUE TITLE
PredictionContextCache

### ISSUE THREAD

**Issue by janyou** [antlr/antlr4-javascript#32]
antlr4/PredictionContext.js/PredictionContextCache.prototype.add
```javascript
PredictionContextCache.prototype.add = function(ctx) {
	......
	var existing = this.cache[ctx];
	if (existing !== null) {
		return existing;
	}
        this.cache[ctx] = ctx;
	.......
};
``` 
if ctx does not exist in cache,  “existing”is equal to“undefined”,  “existing !== null”is  true.
code
```javascript
this.cache[ctx] = ctx;
```
will never be called. Cache is never used 

may change
```javascript
if (existing !== null){
```
to
```javascript
if (existing){
```

or change
```javascript
var existing = this.cache[ctx];
```
to

```javascript
var existing = this.cache[ctx]||null;
```

P.S.
when execute
```javascript
cache[ctx]
```
will call 
```javascript
ctx.toString() 
```
**toString() ** function will be called many times.
javascript  can't use object  key. Lexer  and Parser are slow.

**Comment by janyou** [comment]
P.S.
when execute
```javascript
cache[ctx]
```
will call 
```javascript
ctx.toString() 
```
"toString()" function will be called many times.
javascript  can't use object  key. Lexer  and Parser are slow.

**Comment by ericvergnaud** [comment]
Hi,
thanks for reporting the issue, indeed it should be var existing = this.cache[ctx] || null;
not sure where you take it that "javascript can't use object key", when it actually works.
Yes javascript is slow compared to java or sharp.
Antlr relies largely on maps, like many compute intensive pieces of technology.
The lack of efficient maps in javascript cannot be worked around.

**Comment by janyou** [comment]
Use object as hash table in Javascript

```javascript
var cache={}
var ctx={
    toString:function(){
        return "ctx_name";
    }
}

cache[ctx] =ctx
for(var property in cache ){
    if(cache.hasOwnProperty(property)){
        console.log(property)  //output ctx_name
    }
}
```

When put  ctx object in cache
```javascript
cache[ctx] =ctx
```
The ‘key’ is ctx.toString(), not ctx object.
So ‘toString()’ function will be called many times.

**Comment by ericvergnaud** [comment]
antlr is already using object as hashtable...
( not saying the speed cannot be improved )
