### ISSUE TITLE
/usr/bin/nodejs cannot be found by default BaseTest

### ISSUE THREAD

**Issue by sharwell** [antlr/antlr4-javascript#35]
On a default installation of Ubuntu 15.04, if a user installs nodejs using the following command:

```
sudo apt-get install nodejs
```

The resulting binary is `/usr/bin/nodejs`, which will not be found by the current implementation of `BaseTest`. `BaseTest` should be updated to recognize the nodejs executable in this default installation location.

**Comment by ericvergnaud** [comment]
Please feel free to submit a PR for this. I don't have a fresh Ubuntu 15.04 install to test against.

**Comment by parrt** [comment]
I fixed with https://github.com/antlr/antlr4-javascript/commit/62333178ffc56a891e7e53b38231e9eb3cd25a57
