### ISSUE TITLE
Octal Escapes

### ISSUE THREAD

**Issue by bathos** [antlr/antlr4-javascript#36]
In the serialized ATN, many characters get encoded as octal escapes. Octal escapes in strings were deprecated in 2009, and in strict mode as well as certain ES6 contexts that are inherently strict (like modules), they'll throw. Depending on where the generated code ends up getting used, this could cause problems. Would it be much trouble/worthwhile to switch these to one of the still-legal escapes, hex (\x...) or unicode (\u...)?

**Comment by ericvergnaud** [comment]
Hi,
not much trouble, and thanks for mentioning this, that I was not aware of.
Eric
