### ISSUE TITLE
String.hashCode() bottleneck?

### ISSUE THREAD

**Issue by hce** [antlr/antlr4-javascript#38]
I'm using the JavaScript parser from the sample parsers with the JavaScript antlr4 target. I did a profile in chromium and it looks like String.hashCode() uses more than 60% of the CPU time for parsing a moderately short (100kbytes) java script file. I've changed the hashCode implementation to simply return this.length (a very ugly hack indeed, I agree), but it has improved performance in my case.

Is there a chance the JS target can be implemented without the need for .hashCode()? There seem to be more bottlenecks in the hash related code...

**Comment by ericvergnaud** [comment]
Hi,
interesting question, and the answer is no.
The only substitute for HashMap/Dictionary in JavaScript is Object, and there is no official way to customize the hashing function.
Eric

**Comment by ericvergnaud** [comment]
Not saying that the current implementation cannot be improved

**Comment by ericvergnaud** [comment]
BTW, what is the use case for "parsing a ... javascript file" using antlr4 javascript ?

**Comment by hce** [comment]
The idea is to write a tool not unilke jslint that can run inside a browser...
Anyway, what I didn't mention before is that the java version of the parser needs a few milliseconds where the javascript version needs a couple of seconds. So I'm looking for ways to improve the performance.

**Comment by ericvergnaud** [comment]
Probably the most promising approach would be to have a bunch of contributeHashCode functions that receive the current hash code and return an augmented one.
There are roughly 30 places where this need to be done (everywhere there is a hashFunction).
If you wish to explore this, please note that the jqvqscript runtime is now located here:
https://github.com/antlr/antlr4/tree/master/runtime/JavaScript <https://github.com/antlr/antlr4/tree/master/runtime/JavaScript>

Eric

**Comment by hce** [comment]
Alright, thank you. I don't know when yet, but I'll definitely look into it.
