### ISSUE TITLE
Incorrect export in tree/index.js

### ISSUE THREAD

**Issue by jeroencranendonk-wf** [antlr/antlr4-javascript#43]
https://github.com/antlr/antlr4-javascript/blob/master/src/antlr4/tree/index.js#L2 should read `exports.Trees = require('./Trees').Trees;`

**Comment by ericvergnaud** [comment]
Hi,
this project has moved under the main antrl4 repo.
Eric

**Comment by jeroencranendonk-wf** [comment]
@ericvergnaud The published package on the public npm registry (https://www.npmjs.com/package/antlr4) still lists this repo as the source. Will that be addressed?

**Comment by ericvergnaud** [comment]
Done, see PR #1040
